services:
  - type: web
    name: smart-discussion-forum
    env: docker
    plan: free
    envVars:
      - key: APP_NAME
        value: Smart Discussion Forum
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://smart-discussion-forum.onrender.com
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: studdit-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: QUEUE_CONNECTION
        value: sync
      - key: CACHE_STORE
        value: database
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: error

databases:
  - name: studdit-db
    databaseName: studdit
    user: studdit
    plan: free
